FROM golang:1.17-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo .

FROM alpine:3.15
RUN apk --no-cache add ca-certificates
COPY --from=builder /app/echod .
EXPOSE 3000
CMD ["/echod"]
