# Based on https://awesome-prometheus-alerts.grep.to/rules
groups:
  - name: Envoy
    rules:
      - alert: InstanceDown 
        expr: up{job="envoy"} < 1 
        for: 1m

  - name: Echod
    rules:
      - alert: InstanceDown 
        expr: up{job="echod"} < 1
        for: 5m

      - alert: HighRequestLatency 
        expr: rate(http_request_duration_milliseconds_sum[5m]) / rate(http_request_duration_milliseconds_count[5m]) > 0.5
        for: 1m
        annotations:
          summary: Http high request latency
          description: "Echod average requests execution is longer than 500ms."

      - alert: HttpLatency99Percentile
        expr: histogram_quantile(0.99, rate(http_request_duration_milliseconds_bucket[5m])) > 1
        for: 1m
        annotations:
          summary: Echod latency 99 percentile
          description: "Echod 1% slowest requests are longer than 1s."

      - alert: HttpHigh5xxErrorRate 
        expr: sum(rate(http_requests_total{status=~"5.*"}[5m])) / sum(rate(http_requests_total[5m])) * 100 > 5
        for: 1m
        annotations:
          summary: Http high 5xx error rate
          description: "High percentage of HTTP 5xx responses in Echod."
