name: Deploy

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.17.3'

      - name: Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0

          golangci-lint run

      - name: Test
        run: go test -v ./...

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          username: neemiasjnr
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup Docker
        id: buildx
        uses: docker/setup-buildx-action@v1
        if: ${{ github.ref == 'refs/heads/master' }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          context: ./
          file: ./Dockerfile-envoy
          push: true
          tags: neemiasjnr/echod:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        if: ${{ github.ref == 'refs/heads/master' }}
